### ISSUE TITLE
Cannot build RapidCFD-dev

### ISSUE THREAD

**Issue by scotterdavid** [Atizar/RapidCFD-dev#15]
Hello,

I'm trying to build RapidCFD on an Intel cluster, and I'm seeing a large number of errors. That is , errors relating to ambiguous functions. For example:

error: call of overloaded 'sin(double&)' is ambiguous

I'm building the package as advised in the web documentation. That is, using OpenMPI 1.8.4, GNU compilers 4.8.1 and cuda 6.5.14. Could someone please advise me how to eliminate these errors.

Best regards -- David.

**Comment by thilinarmtb** [comment]
This is due to a math function name clash between `std` and `Foam` namespaces. OpenFOAM applications are using latter. You can correct this by modifying CUDA `math_functions.hpp`. Apply the following patch after removing the `txt` extension at the end.

[CUDA-7.0-math_functions.patch.txt](https://github.com/Atizar/RapidCFD-dev/files/106399/CUDA-7.0-math_functions.patch.txt)

**Comment by daniel-jasinski** [comment]
David,

Could you include a build log so that I could examine the problem?

Daniel

**Comment by scotterdavid** [comment]
Thank you for the prompt replies to my question, I have applied the cuda patch as suggested in this thread (thank you), and I'm remaking the installation. I will see how that goes, and I will get back if I need additional help. The build appears to be much cleaner so far, however I will not hold my breath.

David
