### ISSUE TITLE
Provide ThirdParty-*

### ISSUE THREAD

**Issue by aokomoriuta** [Atizar/RapidCFD-dev#2]
Please provide ThirdParty-* to build Rapid-CFD.

I've built Rapid-CFD successfully with [OpenFOAM's ThirdParty-2.3.1](http://downloads.sourceforge.net/foam/ThirdParty-2.3.1.tgz?use_mirror=mesh) because RapidCFD is fork from OpenFOAM-2.3.1. But I also needed to download OpenMPI 1.8.4 (ThirdParty-2.3.1's OpenMPI is 1.6.5).

We need the list which version of ThirParty libs we should use to build and use Rapid-CFD.

Thanks.

**Comment by daniel-jasinski** [comment]
ThirdParty is required only for multi-GPU simulations. On a single GPU no additional libraries are required for building and running.

Currently two MPI libraries were tested:
 * openmpi-1.8.4
 * mvapich2-2.1

Other MPI libraries can also be used since RapidCFD by default does not use direct CUDA-MPI communication.

I uploaded [ThirdParty-dev](http://sourceforge.net/projects/rapidcfd/files/ThirdParty/ThirdParty-dev.zip/download) that is used for building RC. Currently in the Allwmake file the path to CUDA is hardcoded. Maybe it should be configured in bashrc.

**Comment by aokomoriuta** [comment]
@daniel-jasinski 
Thanks. I will try this on next weekend and close this issue after confirm that I can build successfully.

**Comment by aokomoriuta** [comment]
I can build RapidCFD with the privided ThirdParty-dev on AWS.

Thank you!

**Comment by daniel-jasinski** [comment]
Great!
