### ISSUE TITLE
How to install RapidCFD

### ISSUE THREAD

**Issue by outbound-pt** [Atizar/RapidCFD-dev#20]
I apologize for my level of ignorance beforehand.

I tried running the Allwmake script and it got me errors saying it wasn in the $WM_PROJECT_DIR folder, so I copied all the files there and ran it again:

`xxx@x-ubuntu:/opt/openfoam231$ sudo ./Allwmake 
./Allwmake: 4: ./Allwmake: wmakeCheckPwd: not found
Error: Current directory is not $WM_PROJECT_DIR
    The environment variables are inconsistent with the installation.
    Check the OpenFOAM entries in your dot-files and source them.`

Any idea where I go from here?

Am I suppose to compile this some other way beforehand?

Thanks for any help you might provide.

**Comment by daniel-jasinski** [comment]
You should put RC source code in directory: _~/RapidCFD_ then you should go to _~/RapidCFD/RapidCFD-dev_ and run _./Allwmake_

**Comment by outbound-pt** [comment]
I still get the same error. I made a RapiCFD directory in the /opt/openfoam231 and home folders, I always get this error.

**Comment by outbound-pt** [comment]
I still can get this to install. Any ideia of what I'm doing wrong?

**Comment by daniel-jasinski** [comment]
Did you put the source code into `<HOME>/RapidCFD/RapidCFD-dev` as I described earlier?

**Comment by outbound-pt** [comment]
Yes, I just tried it right now and get the same error:

`xxx@xxx-ubuntu:~/RapidCFD/RapidCFD-dev$ ./Allwmake
./Allwmake: 4: ./Allwmake: wmakeCheckPwd: not found
Error: Current directory is not $WM_PROJECT_DIR
    The environment variables are inconsistent with the installation.
    Check the OpenFOAM entries in your dot-files and source them.
`

Am I maybe missing some necessary libraries? Anything CUDA related perhaps?

**Comment by outbound-pt** [comment]
Btw, I'm running Ubuntu 14.04 LTS and OpenFOAM 2.3.1

**Comment by daniel-jasinski** [comment]
Did you source settings:
`source ~/RapidCFD/RapidCFD-dev/etc/bashrc`
?

**Comment by outbound-pt** [comment]
Yes, that file is in that folder. I downloaded everything in a compressed folder and extracted.

**Comment by daniel-jasinski** [comment]
But did you source this file?

**Comment by outbound-pt** [comment]
I once again apologize for my ignorance but I'm not sure what you mean by that. I'm not very familiar with Github and usually just download code I need directly, not through the Github desktop application.

**Comment by daniel-jasinski** [comment]
So go to:
`~/RapidCFD/RapidCFD-dev`

then run command:
`source etc/bashrc`

then you should be able to run:
`./Allwmake`

**Comment by outbound-pt** [comment]
Ah OK, never had to run that (still very newbie at Linux as well).

That seemed to work but now I'm getting a plethora of other errors.

For eg:

`+ wmake rhoPimpleDyMFoam
/bin/sh: 1: /home/toze/RapidCFD/RapidCFD-dev/wmake/platforms/linux64Nvcc/wmkdep: not found
make[1]: Entering directory `/home/toze/RapidCFD/RapidCFD-dev/applications/solvers/compressible/rhoPimpleFoam/rhoPimpleDyMFoam'
SOURCE=rhoPimpleDyMFoam.C ;  nvcc -Xptxas -dlcm=cg -m64 -arch=sm_30 -Dlinux64 -DWM_DP -Xcompiler -Wall -Xcompiler -Wextra -Xcompiler -Wno-unused-parameter -Xcompiler -Wno-vla -Xcudafe "--diag_suppress=null_reference" -Xcudafe "--diag_suppress=subscript_out_of_range" -Xcudafe "--diag_suppress=extra_semicolon" -Xcudafe "--diag_suppress=partial_override" -Xcudafe "--diag_suppress=implicit_return_from_non_void_function" -Xcudafe "--diag_suppress=virtual_function_decl_hidden" -O3  -DNoRepository -D__RESTRICT__='__restrict__'  -I.. -I/home/toze/RapidCFD/RapidCFD-dev/src/thermophysicalModels/basic/lnInclude -I/home/toze/RapidCFD/RapidCFD-dev/src/turbulenceModels/compressible/turbulenceModel -I/home/toze/RapidCFD/RapidCFD-dev/src/finiteVolume/cfdTools -I/home/toze/RapidCFD/RapidCFD-dev/src/finiteVolume/lnInclude -I/home/toze/RapidCFD/RapidCFD-dev/src/meshTools/lnInclude -I/home/toze/RapidCFD/RapidCFD-dev/src/sampling/lnInclude -I/home/toze/RapidCFD/RapidCFD-dev/src/fvOptions/lnInclude -I/home/toze/RapidCFD/RapidCFD-dev/src/dynamicFvMesh/lnInclude -I/home/toze/RapidCFD/RapidCFD-dev/src/dynamicMesh/lnInclude -I/home/toze/RapidCFD/RapidCFD-dev/src/meshTools/lnInclude  -IlnInclude -I. -I/home/toze/RapidCFD/RapidCFD-dev/src/OpenFOAM/lnInclude -I/home/toze/RapidCFD/RapidCFD-dev/src/OSspecific/POSIX/lnInclude   -Xcompiler -fPIC -x cu -D__HOST____DEVICE__='__host__ __device__' -o Make/linux64NvccDPOpt/rhoPimpleDyMFoam.o -c $SOURCE
/bin/sh: 1: nvcc: not found
make[1]: *** [Make/linux64NvccDPOpt/rhoPimpleDyMFoam.o] Error 127
make[1]: Target `/home/toze/RapidCFD/RapidCFD-dev/platforms/linux64NvccDPOpt/bin/rhoPimpleDyMFoam' not remade because of errors.
make[1]: Leaving directory `/home/toze/RapidCFD/RapidCFD-dev/applications/solvers/compressible/rhoPimpleFoam/rhoPimpleDyMFoam'
make: *** [rhoPimpleFoam] Error 2
`

Same for quite a few other solvers (not sure if all). Is this to be expected or do I need to source something else?

**Comment by daniel-jasinski** [comment]
Did you install CUDA correctly?

**Comment by outbound-pt** [comment]
Probably not.

To be honest I don't think I have anything other than the drivers for my K2200 installed.

I'm downloading the CUDA libraries now. I'll install that and try again later, then I'll post my results here.

Thank you very much for all your help, and your patience most of all. :)

**Comment by outbound-pt** [comment]
OK, so I was having toruble installing the Cuda toolkit because of the Nvidia driver but I got that installed and have the latest driver.

I'm still getting errors when running Allwmake (see attached txt file). It doesn't seem to be naming all solvers so Iḿ wondering if this error messages are pertaining to some specific issues.

How would I run a test case to see if it's working?

[rapidcfdmake .txt](https://github.com/Atizar/RapidCFD-dev/files/296721/rapidcfdmake.txt)

**Comment by daniel-jasinski** [comment]
In the file you send there are no errors.
Not all solvers in RC are built.
You can run test cases from regular OpenFOAM.

**Comment by outbound-pt** [comment]
Ah well, joke's on me then because I thought I was missing something and meanwhile I was looking at old issues and noticed I didn't have the nvcc installed so I tried installing that and rerunning Allwmake, and that generated a lot of errors, so many I ended up stopping the process. Right now all the alias for the OpenFOAM solvers seem to have gone kaput so I think I'll have to reinstall OF or manually reconfigure the aliases.

A final question though, to run OF with RapidCFD do I need to type any extra commands into the console when running the solvers (like the MPI commands) or does RapidCFD just integrate into the solvers and it will just run regardless?

**Comment by daniel-jasinski** [comment]
I do not fully understand your last question. RC can be run exactly the same way as OF.

**Comment by KingKraut** [comment]
Hi all,

I am interested in RapidCFD for use with GPUs. 

In the Install-Wiki I read, that OpenMPI with the option --with-cuda needs to be situated in the folder ThirdParty-dev as is the OpenFOAM convention. Do I understand correctly, that besides the RapidCFD-dev folder I need a folder with this exact name "ThirdParty-dev" where simply the OpenMPI folder lies and is installed?
And - this question might be a bit stupid - I do not need a pre-installation of OpenFOAM (I read somewhere, that version 2.3.1 is required?) to use RapidCFD? RapidCFD basically replaces OpenFOAM right?

Secondly I have CUDA-version 7.5 installed on my system with two Tesla K80 GPUs. 
Is it worth giving a try with version 7.5 or should I rather go back and install version 6.5, too?

So in the end, when I have the two folders RapidCFD-dev and ThirdParty-dev I simply run the Allwmake script and this (hopefully) works?
I understand the solvers are based on OpenFOAM-v2.3.1? So if I want to port a custom solver (based on pisoFoam, which I saw is included in RapidCFD) how are my chances, that this will work? Of course adapting my custom solver as much as possible to the pisoFoam solver from RapidCFD...

Thanks a lot for all help!!

Best regards
Johannes Martens

**Comment by daniel-jasinski** [comment]
ThirdParty-dev is only required if you want to run RC on multiple GPUs. If so, you need OpenMPI 1.8 or later, and preferably the latest available since CUDA support is under continuous development.

Original OpenFOAM is only required for pre-processing - mesh generation and case decomposition. If you already had cases prepared you do not need the original OF.

CUDA 7.5 is fine and CUDA 8.0 would be even better since its compiler is much faster than in the previous versions.

If you are writing custom solver similar to simpleFoam it will most likely compile correctly under RC. The only issue may be function name clashes, but that is very easy to fix.

**Comment by KingKraut** [comment]
Thanks a lot for your fast response. 
I will try and continue with the installation - for one GPU first, and get back with news as soon as possible...

**Comment by KingKraut** [comment]
One more thing.
This might be a stupid question, but I am a little confused right now. Do I actually need an installation of gcc-4.8.4 or any other version at all? Since RapidCFD source files are compiled with nvcc. 
When sourcing the bashrc, I don't need to set any variables right? Like foamCompiler, WM_COMPILER, WM_MPLIB, or others...)

It is really only the two steps described above in the directory
~/RapidCFD/RapidCFD-dev

then run command:
source etc/bashrc

then you should be able to run:
./Allwmake

Thanks again

**Comment by KingKraut** [comment]
I just tried running the Allwmake and got the attached output.
Can you help me with this?
Thanks a lot!!

[log_RapidCFD_Allwmake.txt](https://github.com/Atizar/RapidCFD-dev/files/625127/log_RapidCFD_Allwmake.txt)

**Comment by daniel-jasinski** [comment]
You need GCC because NVCC is not an actual compiler but a compiler driver that needs a native compiler to handle host code and build the executable. 

You just need to source the etc/bashrc file to configure the environment if you properly put the sources into ~/RapidCFD/RapidCFD-dev directory.  From the attached file it seams that your sources are in another location than specified here: https://github.com/Atizar/RapidCFD-dev/blob/master/etc/bashrc#L45

**Comment by KingKraut** [comment]
Ok, thanks for your response.

I changed the gcc compiler to version 4.9.2. It still gives the same error. I hope it is not a problem, that it is not 4.8.4?

In the bashrc I chommented out line 45 and uncommented line 47 instead, because /opt/$WM_PROJECT is my install-directory for RapidCFD. Is this the problem, then?

Thanks again for your help!!

**Comment by KingKraut** [comment]
Ok, I started a clean install with gcc-4.8.2 and it seems to be working so far

**Comment by KingKraut** [comment]
Does not look to me as if any solver was made so far. 
[log_RapidCFD_Allwmake.txt](https://github.com/Atizar/RapidCFD-dev/files/627274/log_RapidCFD_Allwmake.txt)
The folder /opt/RapidCFD/RapidCFD-dev/platforms/linux64NvccDPopt only contains a folder lib but no binaries, either...

What am I doing wrong?

**Comment by LightningLars** [comment]
a) someting is wrong with flex (line 4, line 5). Openfoam2.x only supports flex<2.6
=> serious problem, fix that. compile flex 2.5.x, link flexlexer.h into $FOAM_SRC/OpenFOAM/include/
b) /opt/RapidCFD/RapidCFD-dev/wmake/platforms/linux64Nvcc/wmkdep: No such file or directory
=> this is a serious problem. without files you cant compile. fix that.
c) UOPwrite.C:29:17: fatal error: mpi.h: No such file or directory
=> no mpi.h available. fix that. compile openmpi

**Comment by daniel-jasinski** [comment]
There is something messed up with your compiler installation. An error at line 11: "Error: expecting string instruction after `rep'" . You probably have to update your binutils, similarly to what was suggested here: http://stackoverflow.com/questions/23561136/casablanca-assembly-error-gcc-4-8-1-on-linux-centos

**Comment by KingKraut** [comment]
Thanks a lot for the remark!!

I am currently building RapidCFD with gcc-4.9.2. The above "Error: expecting string instruction after `rep'" has not appeared this time. It is running since a couple of hours now, and the only error appearing so far is with regard to openmpi. However, if I am not planning to use mutliple gpus, I don't need that, right?
I will get back, as soon as I have more news! 

In the meantime, I keep asking myself, if the chosen architecture -arch=sm_30 will cause problems at some point? Since I am compiling for Tesla K80, for which this should actually be set to sm_37, should it not?

Thanks again for all your help!!
 Best regards

**Comment by KingKraut** [comment]
Here is the output from the compilation:
[log_RapidCFD_Allwmake_gcc492.txt](https://github.com/Atizar/RapidCFD-dev/files/633191/log_RapidCFD_Allwmake_gcc492.txt)
It finally crashed, when it did not find lcompressibleTurbulenceModels...
Earlier in the logfile it states there is no space left on device /tmp (line 2645). I guess this is the reason for later errors and why some solvers were not built...

Nevertheless I started an (incompressible) testCase with pisoFoam and RapidCFD seems to be running well enough. However, I had to change the gradSchemes in system/fvSchemes, (which worked well in OF222 and OF301 but are apparently not available here. Have to check if they are simply not existent in OF231...). 

I will now try and compile custom solvers and transport/turbulence models in RapidCFD. Is there anything, where I should be cautious of in this regard?
Can you tell me if swak4Foam is compatible with RapidCFD? This would be very helpful regarding alternative boundary conditions...

Thanks!

**Comment by KingKraut** [comment]
I tried compiling my custom solver however, I get a problem, with the DataEntry.H, which is included right in the beginning of the solver.C. It seems as if it is not being included properly...
This is the log_file from wmake:
[log_wmake.txt](https://github.com/Atizar/RapidCFD-dev/files/633468/log_wmake.txt)

I suppose the problem is the incomplete compilation of RapidCFD. I googled the error "no space left on device" and I need to set the TMPDIR for gcc492 to a larger directory than /tmp (apparently 512 M was not sufficient?).
Unfortunately I am not very experienced with this kind of stuff, can you tell me how and when to set this properly before running the Allwmake from within RapidCFD-dev?
like this?
export TMPDIR=/path/to/directory

Then I will recompile and hopefully no further errors...

Thanks a lot!!

Thanks

**Comment by KingKraut** [comment]
Just for your information, I managed to compile RapidCFD.

**Comment by daniel-jasinski** [comment]
I am glad you managed to compile RC. 

Here are my answers to questions you asked in previous posts:

You can change architecture -arch=sm_37, this should make applications start a bit faster since the CUDA driver will not have to compile PTX to your specific architecture.

I do not know much about swak4Foam, so I cannot tell in advanced if there will be any compatibility issues.

When you experience the "no space left on device" error, do you still have some space on your drive?

In a separate thread I answered you question regarding custom solver error.

**Comment by KingKraut** [comment]
Thanks a lot for your fast answers!

I simply exported $TMPDIR to a larger directory as I wrote above and this solved the issue and RapidCFD compiled well. I guess /tmp was just not large enough.
I will try swak4Foam soon enough and let you know how this works...

For now I will work with arch=sm_30 as I just got it compiled. Maybe I will change this later, thanks for the hint!

**Comment by jygd** [comment]
KingKraut I install the RapidCFD for multi-GPUs, Thanks, but i compared a Tesla k40 with 2 core Xeon E-5 2630 v4 and this woks same for a 1000 000 cells simulation with icoFoam. Do you know some for optmizate the GPUs? I think that is slowly

**Comment by Dcn303** [comment]
> You should put RC source code in directory: _~/RapidCFD_ then you should go to _~/RapidCFD/RapidCFD-dev_ and run _./Allwmake_

hi [daniel-jasinski](https://github.com/daniel-jasinski)
can you clearify by what how to RC the source code. I didn't get what RC means

**Comment by Dcn303** [comment]
> You should put RC source code in directory: _~/RapidCFD_ then you should go to _~/RapidCFD/RapidCFD-d_

Hi daniel-jasinski i am confuse as to how to RC the source code . i am not getting what do you meant by RC

**Comment by TonkomoLLC** [comment]
Probably `RC` = `RapidCFD`
