### ISSUE TITLE
Installation in Ubuntu 19.04 with Cuda 10.1

### ISSUE THREAD

**Issue by hgasca** [Atizar/RapidCFD-dev#63]
Goood morning, I am installing Rapid CFD in Ubuntu 19.04 with CUDA 10.1. I am having the error:
collect2: error: ld returned 1 exit status
make: *** [/home/hgasca/RapidCFD/RapidCFD-dev/wmake/Makefile:150: /home/hgasca/RapidCFD/RapidCFD-dev/platforms/linux64NvccDPOpt/bin/driftFluxFoam] Error 1

Also I have any warnings like:
warning: catching polymorphic type ‘class std::bad_cast’ by value [-Wcatch-value=]

I Agreee your help.

**Comment by TonkomoLLC** [comment]
Hello,

`collect2: error: ld returned 1 exit status` is probably due to another underlying error. For example, if some other library failed to compile, then that library won't be available for driftFluxFoam.  

Thus far I have not noticed any problems with ignoring warnings thrown during the compilation of RapidCFD, as long as there are no compile errors.


I've compiled (plus minimally tested) RapidCFD with Ubuntu 18.04 + CUDA 10.1. I have not tried Ubuntu 19.04. 

Firstly, please ensure that you followed the instructions that I used to compile with CUDA 10.1, in #59. Maybe this will solve your problem and you need not follow the next set of advice.

However, if you already tried these instructions in #59 , maybe there are some changes to gcc and its toolchain that are not compatible with OpenFOAM 2.3.x and/or RapidCFD?

If you need to follow this path, there are instructions [here](https://openfoamwiki.net/index.php/Installation/Linux/OpenFOAM-2.3.1/Ubuntu#Ubuntu_18.04) for compiling OpenFOAM 2.3.1 with Ubuntu 18.04, but not 19.04.  

If OpenFOAM 2.3.x fails to compile with Ubuntu 19.04 using the Ubuntu 18.04 instructions, maybe there is a common problem with compiling OpenFOAM 2.3-era versions with the Ubuntu 19.04 system. If OpenFOAM 2.3.x does compile with Ubuntu 19.04, maybe you can use this experience to hone in on the problem with RapidCFD.

I hope this gives you some ideas for the way forward.  

Best regards,

Eric

**Comment by hgasca** [comment]
Thank You Erick, 
I made the #59 steps but the error persists. Now I will go to test with the OpenFOAM 2.3x test and I will tell you the results. Bi now I have a question about two messages. 
1. Installing ThirdParty-dev the message is: 
--- MPI Extension cr
checking if MPI Extension cr can compile... no

============================================================================
== Contributed software setup
============================================================================

*** Configuring contributed software packages
checking which contributed software packages should be disabled... 

--- vt (m4 configuration macro)
checking whether PMPI is enabled... no
configure: WARNING: **************************************************************
configure: WARNING: *** VampirTrace cannot be built due to disabled MPI profiling.
configure: WARNING: *** Pausing to give you time to read this message...
configure: WARNING: **************************************************************
what it means?

2. This message is normal?:

Note: ignore spurious warnings about missing mpicxx.h headers

wmake libso mpi
wmakeLnInclude: linking include files to ./lnInclude
Making dependency list for source file UOPwrite.C
could not open file omp.h for source file UOPwrite.C due to No such file or directory
could not open file openmpi/ompi/mpi/cxx/mpicxx.h for source file UOPwrite.C due to No such file or directory
Making dependency list for source file UIPread.C
could not open file omp.h for source file UIPread.C due to No such file or directory
could not open file openmpi/ompi/mpi/cxx/mpicxx.h for source file UIPread.C due to No such file or directory
Making dependency list for source file UPstream.C
could not open file omp.h for source file UPstream.C due to No such file or directory
could not open file openmpi/ompi/mpi/cxx/mpicxx.h for source file UPstream.C due to No such file or directory
Making dependency list for source file PstreamGlobals.C
could not open file omp.h for source file PstreamGlobals.C due to No such file or directory
could not open file openmpi/ompi/mpi/cxx/mpicxx.h for source file PstreamGlobals.C due to No such file or directory

B.R.

**Comment by TonkomoLLC** [comment]
Hello, B.R.,

Here is my recommendation for troubleshooting your problem:

Re: ThirdParty-dev, firstly, please ensure that there is no conflicting ThirdParty-dev, e.g., from a copy of OpenFOAM-dev also installed on your system.

Next, obtain a fresh copy of ThirdParty-dev from [here](http://sourceforge.net/projects/rapidcfd/files/ThirdParty/ThirdParty-dev.zip/download), as discussed in issue #2.  

My notes show that I edited ThirdParty-dev/Allwmake (here attached as Allwmake.txt so GitHub will accept the attachment; please rename if you use this file), I think I added a semicolon somewhere, but I didn't keep notes of my specific change to the Allwmake file.  

You may need to specifically `wclean` RapidCFD-dev/src/Pstream, and recompile RapidCFD-dev/src/Pstream with `wmake`. 

Hopefully now your mpi errors disappear upon recompiling RapidCFD.

By the way, If you are not using multiple GPU cards, you can compile RapidCFD without ThirdParty-dev, and just ignore the mpi warnings when Pstream is compiled.  This is the easiest way to get RapidCFD working if you do not have multiple GPU's.

[Allwmake.txt](https://github.com/Atizar/RapidCFD-dev/files/3272422/Allwmake.txt)

Good luck with your compiling. Hopefully compiling OpenFOAM 2.3.x helps with troubleshooting.

Best regards,

Eric

**Comment by hgasca** [comment]
Hello Erick, 

Thank you for your help, with you guide, I finish solved the issue installing gcc-6 and g++-6.
After this installation choosing them by:
update-alternatives --config gcc
Then the installation worked like a charm.

Best regards,

Hernando Gasca
