### ISSUE TITLE
Coupling RapidCFD with CFDEM/LIGGGHTS

### ISSUE THREAD

**Issue by name7891** [Atizar/RapidCFD-dev#64]
Greetings,

I would like to know whether it is possible to couple RapidCFD with CFDEM/LIGGGHTS

(Documentation on how to do it with OpenFoam https://www.cfdem.com/media/CFDEM/docu/CFDEMcoupling_Manual.html)
Wasn't able to do it till now.

Thank you very much in advance.

Greetings,
me

**Comment by TonkomoLLC** [comment]
Hello,

My suspicion is that will not be easy or efficient to use the RapidCFD base code for a CFDEM solver.

1. LIGGGHTS is not GPU enabled, as far as I know.

2. The CFDEM libraries are not setup for GPU calculations.

3. RapidCFD is based on OpenFOAM 2.3.x, and presently CFDEM is based on OpenFOAM 5.x (maybe the current version of CFDEM still works with OF 2.3.x, or for sure you can use an earlier version of CFDEM, to get around this concern).

But the main idea of RapidCFD is to minimize data transfer between CPU memory and the GPU. Without porting the CFDEM libraries (or LIGGGHTS, too?)  for GPU, I am not sure this will be as speedy as some of the other results people have discussed with RapidCFD, since data will need to be transferred between CPU and GPU (this is slow).

Finally, I don't think that all calculations lend themselves to speedup on the GPU, even if you were to port CFDEM libraries and/or LIGGGHTS to GPU. One would need to examine if the type of calculations done by CFDEM and/or LIGGGHTS are matrix type calculations that lend themselves to GPU speedup. If not, then after all the work is done, the speedup may not be so impressive.

Sorry for all the issues.. but I hope I gave you one points to consider.

Best regards,

Eric

**Comment by name7891** [comment]
I totally forgot to respond. I really thank you for your extremely fast and detailed answer.

Greetings,
me
